name: GolangCI-Lint
on:
  workflow_dispatch:
  pull_request:
    branches:
      - '**/golang-**'
  # push:
  #   branches:
  #     - "master"

jobs:
  lint:
    name: GolangCI-Lint
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: 1.19

      - name: Set GOROOT
        run: echo "GOROOT=$(go env GOROOT)" >> $GITHUB_ENV

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          # https://github.com/golangci/golangci-lint/releases/tag/v1.50.1
          version: v1.50.1
        env:
          GOROOT: ${{ env.GOROOT }}
